# Generated by Django 4.1.2 on 2024-02-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=3, default=None, max_digits=100000)),
                ('status', models.CharField(default=None, max_length=1000)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateField()),
                ('deleted_at', models.DateField(blank=True, default=None)),
            ],
        ),
    ]
