# Generated by Django 4.1.2 on 2024-02-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Account', '0002_initial'),
        ('Order_Details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Customer_Account.customeraccount'),
            preserve_default=False,
        ),
    ]
