# Generated by Django 4.1.2 on 2024-02-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Details', '0002_order_details_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
