# Generated by Django 4.1.2 on 2024-02-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller_Shop', '0001_initial'),
        ('Seller_Account', '0008_selleraccount_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default=None, max_length=100)),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Seller_Account.selleraccount', verbose_name='Seller')),
                ('shop_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Seller_Shop.sellershop', verbose_name='Shop')),
            ],
        ),
    ]
