# Generated by Django 4.1.2 on 2024-02-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Category', '0001_initial'),
        ('Seller_Account', '0002_alter_selleraccount_user_id'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Category.product_categories', verbose_name='Category ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_Account.selleraccount', verbose_name='Seller ID'),
        ),
    ]
