# Generated by Django 4.1.2 on 2024-02-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller_Account', '0009_remove_selleraccount_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(default=None, max_length=100)),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Seller_Account.selleraccount', verbose_name='Seller')),
            ],
        ),
    ]
