# Generated by Django 4.1.2 on 2024-02-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller_Account', '0008_selleraccount_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default=None, max_length=100)),
                ('account_number', models.PositiveIntegerField(default=None)),
                ('bsb_code', models.CharField(default=None, max_length=100)),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Seller_Account.selleraccount', verbose_name='Seller')),
            ],
        ),
    ]
