# Generated by Django 4.1.2 on 2024-02-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('Order_Details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=None)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateField()),
                ('deleted_at', models.DateField(blank=True, default=None)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order_Details.order_details', verbose_name='Order details')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='payment details')),
            ],
        ),
    ]
