# Generated by Django 4.1.2 on 2024-02-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('Order_Items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Products'),
        ),
    ]
