# Generated by Django 4.1.2 on 2024-02-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_product_video_alter_product_product_image'),
        ('Order_Items', '0003_alter_order_items_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order_items',
            name='product_id',
            field=models.ManyToManyField(to='Product.product', verbose_name='Products'),
        ),
    ]
