# Generated by Django 4.1.2 on 2024-02-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_product_video_alter_product_product_image'),
        ('Order_Items', '0004_remove_order_items_product_id_order_items_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order_items',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Products'),
        ),
    ]
