# Generated by Django 4.1.2 on 2024-02-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Account', '0003_alter_customeraccount_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='national_id',
            field=models.CharField(blank=True, default=None, max_length=14, null=True, unique=True),
        ),
    ]
