# Generated by Django 4.1.2 on 2024-02-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Account', '0005_alter_customeraccount_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='national_id',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
