# Generated by Django 4.1.2 on 2024-02-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Account', '0009_remove_customeraccount_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Customer Profile Photos'),
        ),
    ]
