# Generated by Django 4.1.2 on 2024-02-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customuser_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_customer',
        ),
    ]
