# Generated by Django 4.1.2 on 2024-02-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller_Account', '0007_remove_selleraccount_business_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default=None, max_length=100)),
                ('facebook_link', models.CharField(default=None, max_length=100)),
                ('instagram_link', models.CharField(default=None, max_length=100)),
                ('website_link', models.CharField(default=None, max_length=100)),
                ('location', models.CharField(default=None, max_length=100)),
                ('seller_id', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Seller_Account.selleraccount', verbose_name='Seller ID')),
            ],
        ),
    ]
