# Generated by Django 4.1.2 on 2024-02-01 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('business_name', models.TextField(default=None, max_length=50)),
                ('business_field', models.TextField(default=None, max_length=50)),
                ('telephone', models.PositiveIntegerField(default=None)),
                ('created_at', models.DateField(default=None)),
                ('modified_at', models.DateField(auto_now=True)),
                ('user_id', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='seller')),
            ],
        ),
    ]
