# Generated by Django 4.1.2 on 2024-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_Account', '0004_alter_selleraccount_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='national_id',
            field=models.CharField(blank=True, default=None, max_length=14, null=True),
        ),
    ]
