# Generated by Django 4.1.2 on 2024-02-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_Account', '0005_alter_selleraccount_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
