# Generated by Django 4.1.2 on 2024-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_Account', '0007_remove_selleraccount_business_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='address_line1',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='address_line2',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
