# Generated by Django 4.1.2 on 2024-02-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_Account', '0009_remove_selleraccount_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Seller Profile Photos'),
        ),
    ]
