# Generated by Django 4.1.2 on 2024-02-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=None)),
                ('created_at', models.DateField(default=None)),
                ('modified_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(default=None)),
            ],
        ),
    ]
