# Generated by Django 4.1.2 on 2024-02-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_Items', '0003_cart_items_user_id_alter_cart_items_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
