# Generated by Django 4.1.2 on 2024-02-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Account', '0003_alter_customeraccount_user_id'),
        ('Cart_Items', '0004_alter_cart_items_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer_Account.customeraccount', verbose_name='Customer'),
        ),
    ]
