# Generated by Django 4.1.2 on 2024-02-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_product_video_alter_product_product_image'),
        ('Cart_Items', '0005_alter_cart_items_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product in cart'),
        ),
    ]
