# Generated by Django 4.1.2 on 2024-02-04 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart_Items', '0008_remove_cart_items_product_id_cart_items_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='users_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
