# Generated by Django 4.1.2 on 2024-02-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart_Items', '0009_cart_items_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='user_id',
        ),
    ]
