# Generated by Django 4.1.2 on 2024-02-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer_Account', '0002_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=None)),
                ('created_at', models.DateField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer_Account.customeraccount', verbose_name='user')),
            ],
        ),
    ]
