# Generated by Django 4.1.2 on 2024-02-01 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_rating',
            name='rating',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
