# Generated by Django 4.1.2 on 2024-02-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Rating', '0002_alter_product_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_rating',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
    ]
