# Generated by Django 4.1.2 on 2024-02-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_category_id_alter_product_seller_id'),
        ('Customer_Account', '0003_alter_customeraccount_user_id'),
        ('Product_Rating', '0003_alter_product_rating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_rating',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='product_rating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer_Account.customeraccount', verbose_name='Customer ID'),
        ),
    ]
